package com.example.kaio01.agenda_aluno;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;


public class CriaBanco extends SQLiteOpenHelper {

    private static final String NOME_BANCO = "bdAgenda.db";
    private static final int VERSAO = 1;

    public CriaBanco(Context context){
        super(context, NOME_BANCO,null,VERSAO);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        String sql;

        //CRIANDO TABELA ESCOLAS
        sql = "CREATE TABLE ESCOLAS(_ID_ESCOLA INTEGER PRIMARY KEY AUTOINCREMENT,NOME TEXT, ENDERECO TEXT, EMAIL TEXT, TELEFONE TEXT )";
        db.execSQL(sql);

       //CRIANDO TABELA CURSOS
        sql = "CREATE TABLE CURSOS(_ID_CURSO INTEGER PRIMARY KEY AUTOINCREMENT, DESCRICAO TEXT, TIPO TEXT, ANO TEXT, COORDENADOR TEXT, PERIODO TEXT, COD_ESCOLA INTEGER, FOREIGN KEY(COD_ESCOLA) REFERENCES ESCOLA(_ID_ESCOLA) )";
        db.execSQL(sql);

        //CRIANDO TABELA TURMAS
        sql= "CREATE TABLE TURMAS(_ID_TURMA INTEGER PRIMARY KEY AUTOINCREMENT, DESCICAO TEXT,COD_CURSO INTEGER, FOREIGN KEY(COD_CURSO) REFERENCES CURSOS(_ID_CURSO))";
        db.execSQL(sql);

        //CRIANDO TABELA AULAS
        sql = "CREATE TABLE AULAS(_ID_AULA INTEGER PRIMARY KEY AUTOINCREMENT, DESCRICAO TEXT, COD_DISCENTE INTEGER, COD_DOCENTE INTEGER, FOREIGN KEY (COD_DISCENTE) REFERENCES DISCENTES(_ID_DISCENTE), FOREIGN KEY (COD_DOCENTE) REFERENCES DOCENTEs (_ID_DOCENTE))";
        db.execSQL(sql);

        //CRIANDO TABELA ARMARIOS
        sql = "CREATE TABLE ARMARIOS(_ID_ARMARIO INTEGER PRIMARY KEY, COD_DOCENTE INTEGER, COD_DISCENTE INTEGER, CONTEUDO TEXT, FOREIGN KEY (COD_DOCENTE) REFERENCES DOCENTES(_ID_DOCENTE), FOREIGN KEY (COD_DISCENTE) REFERENCES DISCENTES(_ID_DISCENTE))";
        db.execSQL(sql);

        //CRIANDO TABELA USUARIOS
        sql = "CREATE TABLE USUARIOS(_ID_USUARIO INTEGER PRIMARY KEY AUTOINCREMENT, EMAIL TEXT, NOME TEXT, SENHA TEXT, TELEFONE TEXT, DATA_NASC TEXT, COD_TIPO_USUARIO INTEGER)";
        db.execSQL(sql);

        //CRIANDO TABELA MURAL
        sql = "CREATE TABLE MURAL(_ID_MURAL INTEGER PRIMARY KEY AUTOINCREMENT, POSTAGEM TEXT, COD_USUARIO INTEGER, FOREIGN KEY (COD_USUARIO) REFERENCES USUARIOS(_ID_USUARIO) )";
        db.execSQL(sql);

    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        db.execSQL("DROP TABLE IF EXISTS ESCOLAS");
        db.execSQL("DROP TABLE IF EXISTS CURSOS");
        db.execSQL("DROP TABLE IF EXISTS TURMAS");
        db.execSQL("DROP TABLE IF EXISTS AULAS");
        db.execSQL("DROP TABLE IF EXISTS ARMARIOS");
        db.execSQL("DROP TABLE IF EXISTS USUARIOS");
        db.execSQL("DROP TABLE IF EXISTS MURAL");


        onCreate(db);
    }
}
